# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GotoBrowser < Formula
  desc "URL shortcut manager — open browser links from your terminal"
  homepage "https://github.com/felix-hatr/goto-browser"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/felix-hatr/goto-browser/releases/download/v1.0.0/goto-browser_1.0.0_darwin_amd64.tar.gz"
    sha256 "8d90822844ea2f0137ee287d021fe40fdd5f89012e291b1fb857530dcee7e850"

    define_method(:install) do
      bin.install "zebro"
      bash_completion.install "completions/zebro.bash" => "zebro"
      zsh_completion.install "completions/zebro.zsh" => "_zebro"
      fish_completion.install "completions/zebro.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/felix-hatr/goto-browser/releases/download/v1.0.0/goto-browser_1.0.0_darwin_arm64.tar.gz"
    sha256 "0683b202d8f0e04da5b106d23904b76cfff065630c24afa2eaa1cdcf220711c9"

    define_method(:install) do
      bin.install "zebro"
      bash_completion.install "completions/zebro.bash" => "zebro"
      zsh_completion.install "completions/zebro.zsh" => "_zebro"
      fish_completion.install "completions/zebro.fish"
    end
  end

  test do
    system "#{bin}/zebro", "--version"
  end
end
