# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GotoBrowser < Formula
  desc "URL shortcut manager — open browser links from your terminal"
  homepage "https://github.com/felix-hatr/goto-browser"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/felix-hatr/goto-browser/releases/download/v1.0.0/goto-browser_1.0.0_darwin_amd64.tar.gz"
    sha256 "25d13cb2b5aee12201e1acd6a42438382fb2cc912a7225f83fff9840e25b0fd7"

    define_method(:install) do
      bin.install "zebro"
      bash_completion.install "completions/zebro.bash" => "zebro"
      zsh_completion.install "completions/zebro.zsh" => "_zebro"
      fish_completion.install "completions/zebro.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/felix-hatr/goto-browser/releases/download/v1.0.0/goto-browser_1.0.0_darwin_arm64.tar.gz"
    sha256 "aeb8c4aac8526e8322ed1bef29aed0d3dce5d7bd2ee16a188813165a13de4ddf"

    define_method(:install) do
      bin.install "zebro"
      bash_completion.install "completions/zebro.bash" => "zebro"
      zsh_completion.install "completions/zebro.zsh" => "_zebro"
      fish_completion.install "completions/zebro.fish"
    end
  end

  test do
    system "#{bin}/zebro", "--version"
  end
end
