# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GotoBrowser < Formula
  desc "URL shortcut manager — open browser links from your terminal"
  homepage "https://github.com/felix-hatr/goto-browser"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/felix-hatr/goto-browser/releases/download/v1.0.0/goto-browser_1.0.0_darwin_amd64.tar.gz"
    sha256 "4600525efcf50f2313f6cadad1de10b12ec354ff5def1efede6cb7b5a69b8111"

    define_method(:install) do
      bin.install "zebro"
      bash_completion.install "completions/zebro.bash" => "zebro"
      zsh_completion.install "completions/zebro.zsh" => "_zebro"
      fish_completion.install "completions/zebro.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/felix-hatr/goto-browser/releases/download/v1.0.0/goto-browser_1.0.0_darwin_arm64.tar.gz"
    sha256 "e9157ed84eb9d7b0de90ba86efe5093f2b0fa09482a457f2aef5dc3e8512e845"

    define_method(:install) do
      bin.install "zebro"
      bash_completion.install "completions/zebro.bash" => "zebro"
      zsh_completion.install "completions/zebro.zsh" => "_zebro"
      fish_completion.install "completions/zebro.fish"
    end
  end

  test do
    system "#{bin}/zebro", "--version"
  end
end
